;;; File of stub definitions needed because the graphics code has not
;;; yet been ported. [SLB]

(in-package :copycat)

(defvar %graphics-viewport-width%)
(defvar %graphics-viewport-height%)
(defvar %graphics-viewport-x%)
(defvar %graphics-viewport-y%)

(defun clear-window ())
(defun display-ccat ())
(defun display-coderack ())
(defun display-descriptions ())
(defun display-minimal-coderack ())
(defun display-slipnet ())
(defun display-temperature ())
(defun draw-bond-grope (from-obj to-obj)
  (declare (ignore from-obj to-obj)))
(defun draw-correspondence-grope (from-obj to-obj)
  (declare (ignore from-obj to-obj)))
(defun draw-group-grope (left-obj right-obj)
  (declare (ignore left-obj right-obj)))
(defun get-begin-run-time-menu-command ())
(defun get-init-time-menu-command (target-string-input)
  (declare (ignore target-string-input)))
(defun init-answer-graphics ())
(defun init-begin-run-time-menu ())
(defun init-coderack-graphics ())
(defun init-init-time-menu ())
(defun init-minimal-coderack-display ())
(defun init-slipnet-graphics ())
(defun init-workspace-graphics ())
(defun open-window (w h x y)
  (declare (ignore w h x y)))
(defun redraw-graphics ())
(defun update-coderack-display ())
(defun update-minimal-coderack-display ())
(defun update-slipnet-display ())
(defun update-temperature-display ())
